/*
OpenAPI Extension x-auth-id-alias

This specification shows how to use x-auth-id-alias extension for API keys.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x_auth_id_alias

import (
	"bytes"
	"context"
	"encoding/json"
	"encoding/xml"
	"errors"
	"fmt"
	"io"
	"log"
	"mime/multipart"
	"net/http"
	"net/http/httputil"
	"net/url"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"strconv"
	"strings"
	"time"
	"unicode/utf8"

)

var (
	JsonCheck       = regexp.MustCompile(`(?i:(?:application|text)/(?:[^;]+\+)?json)`)
	XmlCheck        = regexp.MustCompile(`(?i:(?:application|text)/(?:[^;]+\+)?xml)`)
	queryParamSplit = regexp.MustCompile(`(^|&)([^&]+)`)
	queryDescape    = strings.NewReplacer( "%5B", "[", "%5D", "]" )
)

// APIClient manages communication with the OpenAPI Extension x-auth-id-alias API v1.0.0
// In most cases there should be only one, shared, APIClient.
type APIClient struct {
	cfg    *Configuration
	common service // Reuse a single struct instead of allocating one for each service on the heap.

	// API Services

	UsageAPI *UsageAPIService
}

type service struct {
	client *APIClient
}

// NewAPIClient creates a new API client. Requires a userAgent string describing your application.
// optionally a custom http.Client to allow for advanced features such as caching.
func NewAPIClient(cfg *Configuration) *APIClient {
	if cfg.HTTPClient == nil {
		cfg.HTTPClient = http.DefaultClient
	}

	c := &APIClient{}
	c.cfg = cfg
	c.common.client = c

	// API Services
	c.UsageAPI = (*UsageAPIService)(&c.common)

	return c
}

func atoi(in string) (int, error) {
	return strconv.Atoi(in)
}

// selectHeaderContentType select a content type from the available list.
func selectHeaderContentType(contentTypes []string) string {
	if len(contentTypes) == 0 {
		return ""
	}
	if contains(contentTypes, "application/json") {
		return "application/json"
	}
	return contentTypes[0] // use the first content type specified in 'consumes'
}

// selectHeaderAccept join all accept types and return
func selectHeaderAccept(accepts []string) string {
	if len(accepts) == 0 {
		return ""
	}

	if contains(accepts, "application/json") {
		return "application/json"
	}

	return strings.Join(accepts, ",")
}

// contains is a case insensitive match, finding needle in a haystack
func contains(haystack []string, needle string) bool {
	for _, a := range haystack {
		if strings.EqualFold(a, needle) {
			return true
		}
	}
	return false
}

// typeCheckParameter is retained for backward compatibility but type checking
// is now primarily handled at compile time via Go 1.18+ generics.
// This function validates that optional parameters are not nil when expected.
func typeCheckParameter(obj interface{}, expected string, name string) error {
	// Make sure there is an object.
	if obj == nil {
		return nil
	}
	// Type checking is handled at compile time via generics.
	// This function is retained for API compatibility.
	return nil
}

// parameterValueToString converts a parameter value to its string representation.
// Uses type assertions instead of reflection for better performance.
func parameterValueToString(obj interface{}, key string) string {
	if obj == nil {
		return ""
	}

	// Handle oneOf/anyOf types with GetActualInstanceValue
	if actualObj, ok := obj.(interface{ GetActualInstanceValue() interface{} }); ok {
		return fmt.Sprintf("%v", actualObj.GetActualInstanceValue())
	}

	// Handle MappedNullable types (pointer structs with ToMap method)
	if param, ok := obj.(MappedNullable); ok {
		dataMap, err := param.ToMap()
		if err != nil {
			return ""
		}
		return fmt.Sprintf("%v", dataMap[key])
	}

	// For all other types, use fmt.Sprint which handles primitives and strings
	return fmt.Sprintf("%v", obj)
}

// parameterAddToHeaderOrQuery adds the provided object to the request header or url query
// supporting deep object syntax. Uses type switches instead of reflection for 3-12x better performance.
func parameterAddToHeaderOrQuery(headerOrQueryParams interface{}, keyPrefix string, obj interface{}, style string, collectionType string) {
	if obj == nil {
		setParameterValue(headerOrQueryParams, keyPrefix, "null", collectionType)
		return
	}

	// Use type switch for efficient type handling without reflection
	switch v := obj.(type) {
	// Handle MappedNullable structs (model types with ToMap method)
	case MappedNullable:
		// Check for nil pointer before calling ToMap to prevent panic
		// This can happen when a pointer to a struct (e.g., *Category) is nil
		// but still matches the MappedNullable interface
		if IsNil(v) {
			return
		}
		dataMap, err := v.ToMap()
		if err != nil {
			return
		}
		parameterAddToHeaderOrQuery(headerOrQueryParams, keyPrefix, dataMap, style, collectionType)
		return

	// Handle time.Time
	case time.Time:
		setParameterValue(headerOrQueryParams, keyPrefix, v.Format(time.RFC3339Nano), collectionType)
		return

	case *time.Time:
		if v == nil {
			return
		}
		setParameterValue(headerOrQueryParams, keyPrefix, v.Format(time.RFC3339Nano), collectionType)
		return

	// Primitive types - use FormatParameter from helpers_generics.go
	case string:
		setParameterValue(headerOrQueryParams, keyPrefix, v, collectionType)
		return
	case *string:
		if v == nil {
			return
		}
		setParameterValue(headerOrQueryParams, keyPrefix, *v, collectionType)
		return
	case int:
		setParameterValue(headerOrQueryParams, keyPrefix, strconv.Itoa(v), collectionType)
		return
	case *int:
		if v == nil {
			return
		}
		setParameterValue(headerOrQueryParams, keyPrefix, strconv.Itoa(*v), collectionType)
		return
	case int32:
		setParameterValue(headerOrQueryParams, keyPrefix, strconv.FormatInt(int64(v), 10), collectionType)
		return
	case *int32:
		if v == nil {
			return
		}
		setParameterValue(headerOrQueryParams, keyPrefix, strconv.FormatInt(int64(*v), 10), collectionType)
		return
	case int64:
		setParameterValue(headerOrQueryParams, keyPrefix, strconv.FormatInt(v, 10), collectionType)
		return
	case *int64:
		if v == nil {
			return
		}
		setParameterValue(headerOrQueryParams, keyPrefix, strconv.FormatInt(*v, 10), collectionType)
		return
	case uint:
		setParameterValue(headerOrQueryParams, keyPrefix, strconv.FormatUint(uint64(v), 10), collectionType)
		return
	case *uint:
		if v == nil {
			return
		}
		setParameterValue(headerOrQueryParams, keyPrefix, strconv.FormatUint(uint64(*v), 10), collectionType)
		return
	case uint32:
		setParameterValue(headerOrQueryParams, keyPrefix, strconv.FormatUint(uint64(v), 10), collectionType)
		return
	case *uint32:
		if v == nil {
			return
		}
		setParameterValue(headerOrQueryParams, keyPrefix, strconv.FormatUint(uint64(*v), 10), collectionType)
		return
	case uint64:
		setParameterValue(headerOrQueryParams, keyPrefix, strconv.FormatUint(v, 10), collectionType)
		return
	case *uint64:
		if v == nil {
			return
		}
		setParameterValue(headerOrQueryParams, keyPrefix, strconv.FormatUint(*v, 10), collectionType)
		return
	case float32:
		setParameterValue(headerOrQueryParams, keyPrefix, strconv.FormatFloat(float64(v), 'g', -1, 32), collectionType)
		return
	case *float32:
		if v == nil {
			return
		}
		setParameterValue(headerOrQueryParams, keyPrefix, strconv.FormatFloat(float64(*v), 'g', -1, 32), collectionType)
		return
	case float64:
		setParameterValue(headerOrQueryParams, keyPrefix, strconv.FormatFloat(v, 'g', -1, 64), collectionType)
		return
	case *float64:
		if v == nil {
			return
		}
		setParameterValue(headerOrQueryParams, keyPrefix, strconv.FormatFloat(*v, 'g', -1, 64), collectionType)
		return
	case bool:
		setParameterValue(headerOrQueryParams, keyPrefix, strconv.FormatBool(v), collectionType)
		return
	case *bool:
		if v == nil {
			return
		}
		setParameterValue(headerOrQueryParams, keyPrefix, strconv.FormatBool(*v), collectionType)
		return

	// Slice types - iterate and add each element
	case []string:
		for i, item := range v {
			keyPrefixForCollectionType := keyPrefix
			if style == "deepObject" {
				keyPrefixForCollectionType = keyPrefix + "[" + strconv.Itoa(i) + "]"
			}
			parameterAddToHeaderOrQuery(headerOrQueryParams, keyPrefixForCollectionType, item, style, collectionType)
		}
		return
	case []int:
		for i, item := range v {
			keyPrefixForCollectionType := keyPrefix
			if style == "deepObject" {
				keyPrefixForCollectionType = keyPrefix + "[" + strconv.Itoa(i) + "]"
			}
			parameterAddToHeaderOrQuery(headerOrQueryParams, keyPrefixForCollectionType, item, style, collectionType)
		}
		return
	case []int32:
		for i, item := range v {
			keyPrefixForCollectionType := keyPrefix
			if style == "deepObject" {
				keyPrefixForCollectionType = keyPrefix + "[" + strconv.Itoa(i) + "]"
			}
			parameterAddToHeaderOrQuery(headerOrQueryParams, keyPrefixForCollectionType, item, style, collectionType)
		}
		return
	case []int64:
		for i, item := range v {
			keyPrefixForCollectionType := keyPrefix
			if style == "deepObject" {
				keyPrefixForCollectionType = keyPrefix + "[" + strconv.Itoa(i) + "]"
			}
			parameterAddToHeaderOrQuery(headerOrQueryParams, keyPrefixForCollectionType, item, style, collectionType)
		}
		return
	case []float32:
		for i, item := range v {
			keyPrefixForCollectionType := keyPrefix
			if style == "deepObject" {
				keyPrefixForCollectionType = keyPrefix + "[" + strconv.Itoa(i) + "]"
			}
			parameterAddToHeaderOrQuery(headerOrQueryParams, keyPrefixForCollectionType, item, style, collectionType)
		}
		return
	case []float64:
		for i, item := range v {
			keyPrefixForCollectionType := keyPrefix
			if style == "deepObject" {
				keyPrefixForCollectionType = keyPrefix + "[" + strconv.Itoa(i) + "]"
			}
			parameterAddToHeaderOrQuery(headerOrQueryParams, keyPrefixForCollectionType, item, style, collectionType)
		}
		return
	case []interface{}:
		for i, item := range v {
			keyPrefixForCollectionType := keyPrefix
			if style == "deepObject" {
				keyPrefixForCollectionType = keyPrefix + "[" + strconv.Itoa(i) + "]"
			}
			parameterAddToHeaderOrQuery(headerOrQueryParams, keyPrefixForCollectionType, item, style, collectionType)
		}
		return

	// Pointer to slice types - dereference and recurse if not nil
	case *[]string:
		if v != nil {
			parameterAddToHeaderOrQuery(headerOrQueryParams, keyPrefix, *v, style, collectionType)
		}
		return
	case *[]int:
		if v != nil {
			parameterAddToHeaderOrQuery(headerOrQueryParams, keyPrefix, *v, style, collectionType)
		}
		return
	case *[]int32:
		if v != nil {
			parameterAddToHeaderOrQuery(headerOrQueryParams, keyPrefix, *v, style, collectionType)
		}
		return
	case *[]int64:
		if v != nil {
			parameterAddToHeaderOrQuery(headerOrQueryParams, keyPrefix, *v, style, collectionType)
		}
		return
	case *[]float32:
		if v != nil {
			parameterAddToHeaderOrQuery(headerOrQueryParams, keyPrefix, *v, style, collectionType)
		}
		return
	case *[]float64:
		if v != nil {
			parameterAddToHeaderOrQuery(headerOrQueryParams, keyPrefix, *v, style, collectionType)
		}
		return
	case *[]interface{}:
		if v != nil {
			parameterAddToHeaderOrQuery(headerOrQueryParams, keyPrefix, *v, style, collectionType)
		}
		return

	// Map type - iterate over keys
	case map[string]interface{}:
		for k, val := range v {
			parameterAddToHeaderOrQuery(headerOrQueryParams, fmt.Sprintf("%s[%s]", keyPrefix, k), val, style, collectionType)
		}
		return
	case map[string]string:
		for k, val := range v {
			parameterAddToHeaderOrQuery(headerOrQueryParams, fmt.Sprintf("%s[%s]", keyPrefix, k), val, style, collectionType)
		}
		return

	default:
		// Fallback: use reflection for slices of custom types (e.g., []Tag, []Category)
		// This is necessary because we can't enumerate all possible struct slice types at compile time
		rv := reflect.ValueOf(obj)
		if rv.Kind() == reflect.Slice {
			for i := 0; i < rv.Len(); i++ {
				keyPrefixForCollectionType := keyPrefix
				if style == "deepObject" {
					keyPrefixForCollectionType = keyPrefix + "[" + strconv.Itoa(i) + "]"
				}
				parameterAddToHeaderOrQuery(headerOrQueryParams, keyPrefixForCollectionType, rv.Index(i).Interface(), style, collectionType)
			}
			return
		}
		// For non-slice types, use fmt.Sprint
		setParameterValue(headerOrQueryParams, keyPrefix, fmt.Sprint(obj), collectionType)
		return
	}
}

// setParameterValue is a helper function that adds a value to either url.Values or map[string]string
func setParameterValue(headerOrQueryParams interface{}, key string, value string, collectionType string) {
	switch valuesMap := headerOrQueryParams.(type) {
	case url.Values:
		if collectionType == "csv" && valuesMap.Get(key) != "" {
			valuesMap.Set(key, valuesMap.Get(key)+","+value)
		} else {
			valuesMap.Add(key, value)
		}
	case map[string]string:
		valuesMap[key] = value
	}
}

// helper for converting interface{} parameters to json strings
func parameterToJson(obj interface{}) (string, error) {
	jsonBuf, err := json.Marshal(obj)
	if err != nil {
		return "", err
	}
	return string(jsonBuf), err
}

// callAPI do the request.
func (c *APIClient) callAPI(request *http.Request) (*http.Response, error) {
	if c.cfg.Debug {
		dump, err := httputil.DumpRequestOut(request, true)
		if err != nil {
			return nil, err
		}
		log.Printf("\n%s\n", string(dump))
	}

	resp, err := c.cfg.HTTPClient.Do(request)
	if err != nil {
		return resp, err
	}

	if c.cfg.Debug {
		dump, err := httputil.DumpResponse(resp, true)
		if err != nil {
			return resp, err
		}
		log.Printf("\n%s\n", string(dump))
	}
	return resp, err
}

// Allow modification of underlying config for alternate implementations and testing
// Caution: modifying the configuration while live can cause data races and potentially unwanted behavior
func (c *APIClient) GetConfig() *Configuration {
	return c.cfg
}

type formFile struct {
		fileBytes []byte
		fileName string
		formFileName string
}

// prepareRequest build the request
func (c *APIClient) prepareRequest(
	ctx context.Context,
	path string, method string,
	postBody interface{},
	headerParams map[string]string,
	queryParams url.Values,
	formParams url.Values,
	formFiles []formFile) (localVarRequest *http.Request, err error) {

	var body *bytes.Buffer

	// Detect postBody type and post.
	if postBody != nil {
		contentType := headerParams["Content-Type"]
		if contentType == "" {
			contentType = detectContentType(postBody)
			headerParams["Content-Type"] = contentType
		}

		body, err = setBody(postBody, contentType)
		if err != nil {
			return nil, err
		}
	}

	// add form parameters and file if available.
	if strings.HasPrefix(headerParams["Content-Type"], "multipart/form-data") && len(formParams) > 0 || (len(formFiles) > 0) {
		if body != nil {
			return nil, errors.New("Cannot specify postBody and multipart form at the same time.")
		}
		body = &bytes.Buffer{}
		w := multipart.NewWriter(body)

		for k, v := range formParams {
			for _, iv := range v {
				if strings.HasPrefix(k, "@") { // file
					err = addFile(w, k[1:], iv)
					if err != nil {
						return nil, err
					}
				} else { // form value
					w.WriteField(k, iv)
				}
			}
		}
		for _, formFile := range formFiles {
			if len(formFile.fileBytes) > 0 && formFile.fileName != "" {
				w.Boundary()
				part, err := w.CreateFormFile(formFile.formFileName, filepath.Base(formFile.fileName))
				if err != nil {
						return nil, err
				}
				_, err = part.Write(formFile.fileBytes)
				if err != nil {
						return nil, err
				}
			}
		}

		// Set the Boundary in the Content-Type
		headerParams["Content-Type"] = w.FormDataContentType()

		// Set Content-Length
		headerParams["Content-Length"] = fmt.Sprintf("%d", body.Len())
		w.Close()
	}

	if strings.HasPrefix(headerParams["Content-Type"], "application/x-www-form-urlencoded") && len(formParams) > 0 {
		if body != nil {
			return nil, errors.New("Cannot specify postBody and x-www-form-urlencoded form at the same time.")
		}
		body = &bytes.Buffer{}
		body.WriteString(formParams.Encode())
		// Set Content-Length
		headerParams["Content-Length"] = fmt.Sprintf("%d", body.Len())
	}

	// Setup path and query parameters
	url, err := url.Parse(path)
	if err != nil {
		return nil, err
	}

	// Override request host, if applicable
	if c.cfg.Host != "" {
		url.Host = c.cfg.Host
	}

	// Override request scheme, if applicable
	if c.cfg.Scheme != "" {
		url.Scheme = c.cfg.Scheme
	}

	// Adding Query Param
	query := url.Query()
	for k, v := range queryParams {
		for _, iv := range v {
			query.Add(k, iv)
		}
	}

	// Encode the parameters.
	url.RawQuery = queryParamSplit.ReplaceAllStringFunc(query.Encode(), func(s string) string {
		pieces := strings.Split(s, "=")
		pieces[0] = queryDescape.Replace(pieces[0])
		return strings.Join(pieces, "=")
	})

	// Generate a new request
	if body != nil {
		localVarRequest, err = http.NewRequest(method, url.String(), body)
	} else {
		localVarRequest, err = http.NewRequest(method, url.String(), nil)
	}
	if err != nil {
		return nil, err
	}

	// add header parameters, if any
	if len(headerParams) > 0 {
		headers := http.Header{}
		for h, v := range headerParams {
			headers[h] = []string{v}
		}
		localVarRequest.Header = headers
	}

	// Add the user agent to the request.
	localVarRequest.Header.Add("User-Agent", c.cfg.UserAgent)

	if ctx != nil {
		// add context to the request
		localVarRequest = localVarRequest.WithContext(ctx)

		// Walk through any authentication.

	}

	for header, value := range c.cfg.DefaultHeader {
		localVarRequest.Header.Add(header, value)
	}
	return localVarRequest, nil
}

func (c *APIClient) decode(v interface{}, b []byte, contentType string) (err error) {
	if len(b) == 0 {
		return nil
	}
	if s, ok := v.(*string); ok {
		*s = string(b)
		return nil
	}
	if f, ok := v.(*os.File); ok {
		f, err = os.CreateTemp("", "HttpClientFile")
		if err != nil {
			return
		}
		_, err = f.Write(b)
		if err != nil {
			return
		}
		_, err = f.Seek(0, io.SeekStart)
		return
	}
	if f, ok := v.(**os.File); ok {
		*f, err = os.CreateTemp("", "HttpClientFile")
		if err != nil {
			return
		}
		_, err = (*f).Write(b)
		if err != nil {
			return
		}
		_, err = (*f).Seek(0, io.SeekStart)
		return
	}
	if XmlCheck.MatchString(contentType) {
		if err = xml.Unmarshal(b, v); err != nil {
			return err
		}
		return nil
	}
	if JsonCheck.MatchString(contentType) {
		if actualObj, ok := v.(interface{ GetActualInstance() interface{} }); ok { // oneOf, anyOf schemas
			if unmarshalObj, ok := actualObj.(interface{ UnmarshalJSON([]byte) error }); ok { // make sure it has UnmarshalJSON defined
				if err = unmarshalObj.UnmarshalJSON(b); err != nil {
					return err
				}
			} else {
				return errors.New("Unknown type with GetActualInstance but no unmarshalObj.UnmarshalJSON defined")
			}
		} else if err = json.Unmarshal(b, v); err != nil { // simple model
			return err
		}
		return nil
	}
	return errors.New("undefined response type")
}

// Add a file to the multipart request
func addFile(w *multipart.Writer, fieldName, path string) error {
	file, err := os.Open(filepath.Clean(path))
	if err != nil {
		return err
	}
	err = file.Close()
	if err != nil {
		return err
	}

	part, err := w.CreateFormFile(fieldName, filepath.Base(path))
	if err != nil {
		return err
	}
	_, err = io.Copy(part, file)

	return err
}

// Set request body from an interface{}
func setBody(body interface{}, contentType string) (bodyBuf *bytes.Buffer, err error) {
	if bodyBuf == nil {
		bodyBuf = &bytes.Buffer{}
	}

	if reader, ok := body.(io.Reader); ok {
		_, err = bodyBuf.ReadFrom(reader)
	} else if fp, ok := body.(*os.File); ok {
		_, err = bodyBuf.ReadFrom(fp)
	} else if b, ok := body.([]byte); ok {
		_, err = bodyBuf.Write(b)
	} else if s, ok := body.(string); ok {
		_, err = bodyBuf.WriteString(s)
	} else if s, ok := body.(*string); ok {
		_, err = bodyBuf.WriteString(*s)
	} else if JsonCheck.MatchString(contentType) {
		err = json.NewEncoder(bodyBuf).Encode(body)
	} else if XmlCheck.MatchString(contentType) {
		var bs []byte
		bs, err = xml.Marshal(body)
		if err == nil {
			bodyBuf.Write(bs)
		}
	}

	if err != nil {
		return nil, err
	}

	if bodyBuf.Len() == 0 {
		err = fmt.Errorf("invalid body type %s\n", contentType)
		return nil, err
	}
	return bodyBuf, nil
}

// detectContentType method is used to figure out `Request.Body` content type for request header.
// Uses type assertions instead of reflection for better performance.
func detectContentType(body interface{}) string {
	// Use type switch instead of reflection for efficient type detection
	switch v := body.(type) {
	case string:
		return "text/plain; charset=utf-8"
	case *string:
		return "text/plain; charset=utf-8"
	case []byte:
		return http.DetectContentType(v)
	// Slice types default to JSON
	case []string, []int, []int32, []int64, []float32, []float64, []interface{}:
		return "application/json; charset=utf-8"
	default:
		// For structs, maps, pointers, and other complex types, default to JSON
		return "application/json; charset=utf-8"
	}
}

// Ripped from https://github.com/gregjones/httpcache/blob/master/httpcache.go
type cacheControl map[string]string

func parseCacheControl(headers http.Header) cacheControl {
	cc := cacheControl{}
	ccHeader := headers.Get("Cache-Control")
	for _, part := range strings.Split(ccHeader, ",") {
		part = strings.Trim(part, " ")
		if part == "" {
			continue
		}
		if strings.ContainsRune(part, '=') {
			keyval := strings.Split(part, "=")
			cc[strings.Trim(keyval[0], " ")] = strings.Trim(keyval[1], ",")
		} else {
			cc[part] = ""
		}
	}
	return cc
}

// CacheExpires helper function to determine remaining time before repeating a request.
func CacheExpires(r *http.Response) time.Time {
	// Figure out when the cache expires.
	var expires time.Time
	now, err := time.Parse(time.RFC1123, r.Header.Get("date"))
	if err != nil {
		return time.Now()
	}
	respCacheControl := parseCacheControl(r.Header)

	if maxAge, ok := respCacheControl["max-age"]; ok {
		lifetime, err := time.ParseDuration(maxAge + "s")
		if err != nil {
			expires = now
		} else {
			expires = now.Add(lifetime)
		}
	} else {
		expiresHeader := r.Header.Get("Expires")
		if expiresHeader != "" {
			expires, err = time.Parse(time.RFC1123, expiresHeader)
			if err != nil {
				expires = now
			}
		}
	}
	return expires
}

func strlen(s string) int {
	return utf8.RuneCountInString(s)
}

// GenericOpenAPIError Provides access to the body, error and model on returned errors.
type GenericOpenAPIError struct {
	body  []byte
	error string
	model interface{}
}

// Error returns non-empty string if there was an error.
func (e GenericOpenAPIError) Error() string {
	return e.error
}

// Body returns the raw bytes of the response
func (e GenericOpenAPIError) Body() []byte {
	return e.body
}

// Model returns the unpacked model of the error
func (e GenericOpenAPIError) Model() interface{} {
	return e.model
}

// RFC7807Error is an interface for RFC 7807 Problem Details error responses.
// Models implementing this interface will have their title and detail fields
// extracted for error formatting.
type RFC7807Error interface {
	GetTitle() string
	GetDetail() string
}

// formatErrorMessage formats error message using title and detail when model implements RFC 7807.
// Uses interface-based approach instead of reflection for better performance.
func formatErrorMessage(status string, v interface{}) string {
	// Try to use RFC7807Error interface first (preferred approach)
	if rfc7807, ok := v.(RFC7807Error); ok {
		title := rfc7807.GetTitle()
		detail := rfc7807.GetDetail()
		if title != "" {
			if detail != "" {
				return strings.TrimSpace(fmt.Sprintf("%s %s (%s)", status, title, detail))
			}
			return strings.TrimSpace(fmt.Sprintf("%s %s", status, title))
		}
	}

	// Fallback: try to extract Title and Detail from struct via getter methods
	// This provides backward compatibility with existing generated models
	type titleGetter interface{ GetTitle() string }
	type detailGetter interface{ GetDetail() string }

	var str string
	if tg, ok := v.(titleGetter); ok {
		str = tg.GetTitle()
	}
	if dg, ok := v.(detailGetter); ok {
		if detail := dg.GetDetail(); detail != "" {
			str = fmt.Sprintf("%s (%s)", str, detail)
		}
	}

	return strings.TrimSpace(fmt.Sprintf("%s %s", status, str))
}
