/*
Test

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"reflect"
	"time"
)

// Ptr is a generic helper that returns a pointer to any value.
// This replaces all the type-specific Ptr* functions with a single generic function.
func Ptr[T any](v T) *T { return &v }

// PtrBool is a helper routine that returns a pointer to given boolean value.
// Deprecated: Use Ptr(v) instead.
func PtrBool(v bool) *bool { return &v }

// PtrInt is a helper routine that returns a pointer to given integer value.
// Deprecated: Use Ptr(v) instead.
func PtrInt(v int) *int { return &v }

// PtrInt32 is a helper routine that returns a pointer to given integer value.
// Deprecated: Use Ptr(v) instead.
func PtrInt32(v int32) *int32 { return &v }

// PtrInt64 is a helper routine that returns a pointer to given integer value.
// Deprecated: Use Ptr(v) instead.
func PtrInt64(v int64) *int64 { return &v }

// PtrFloat32 is a helper routine that returns a pointer to given float value.
// Deprecated: Use Ptr(v) instead.
func PtrFloat32(v float32) *float32 { return &v }

// PtrFloat64 is a helper routine that returns a pointer to given float value.
// Deprecated: Use Ptr(v) instead.
func PtrFloat64(v float64) *float64 { return &v }

// PtrString is a helper routine that returns a pointer to given string value.
// Deprecated: Use Ptr(v) instead.
func PtrString(v string) *string { return &v }

// PtrTime is helper routine that returns a pointer to given Time value.
// Deprecated: Use Ptr(v) instead.
func PtrTime(v time.Time) *time.Time { return &v }

// ============================================================================
// Generic Nullable Type
// ============================================================================

// Nullable is a generic wrapper for nullable values that tracks whether
// a value has been explicitly set (including to null) vs left unset.
// This replaces the repetitive NullableBool, NullableInt, etc. types.
type Nullable[T any] struct {
	value *T
	isSet bool
}

// Get returns a pointer to the value, or nil if not set.
func (v Nullable[T]) Get() *T {
	return v.value
}

// Set stores the value and marks it as set.
func (v *Nullable[T]) Set(val *T) {
	v.value = val
	v.isSet = true
}

// IsSet returns true if a value has been set (including explicit nil).
func (v Nullable[T]) IsSet() bool {
	return v.isSet
}

// Unset clears the value and marks it as not set.
func (v *Nullable[T]) Unset() {
	v.value = nil
	v.isSet = false
}

// NewNullable creates a new Nullable with the given value.
func NewNullable[T any](val *T) *Nullable[T] {
	return &Nullable[T]{value: val, isSet: true}
}

// MarshalJSON implements json.Marshaler.
func (v Nullable[T]) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

// UnmarshalJSON implements json.Unmarshaler.
func (v *Nullable[T]) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

// Type aliases for backward compatibility with existing code.
// These allow existing code using NullableBool, NullableInt, etc. to continue working.

// NullableBool is a nullable boolean type.
// Deprecated: Use Nullable[bool] directly for new code.
type NullableBool = Nullable[bool]

// NullableInt is a nullable int type.
// Deprecated: Use Nullable[int] directly for new code.
type NullableInt = Nullable[int]

// NullableInt32 is a nullable int32 type.
// Deprecated: Use Nullable[int32] directly for new code.
type NullableInt32 = Nullable[int32]

// NullableInt64 is a nullable int64 type.
// Deprecated: Use Nullable[int64] directly for new code.
type NullableInt64 = Nullable[int64]

// NullableFloat32 is a nullable float32 type.
// Deprecated: Use Nullable[float32] directly for new code.
type NullableFloat32 = Nullable[float32]

// NullableFloat64 is a nullable float64 type.
// Deprecated: Use Nullable[float64] directly for new code.
type NullableFloat64 = Nullable[float64]

// NullableString is a nullable string type.
// Deprecated: Use Nullable[string] directly for new code.
type NullableString = Nullable[string]

// NullableTime is a nullable time.Time type.
// Deprecated: Use Nullable[time.Time] directly for new code.
type NullableTime = Nullable[time.Time]

// Legacy constructor functions for backward compatibility.
// These wrap NewNullable for each specific type.

// NewNullableBool creates a new NullableBool.
// Deprecated: Use NewNullable(val) instead.
func NewNullableBool(val *bool) *NullableBool {
	return NewNullable(val)
}

// NewNullableInt creates a new NullableInt.
// Deprecated: Use NewNullable(val) instead.
func NewNullableInt(val *int) *NullableInt {
	return NewNullable(val)
}

// NewNullableInt32 creates a new NullableInt32.
// Deprecated: Use NewNullable(val) instead.
func NewNullableInt32(val *int32) *NullableInt32 {
	return NewNullable(val)
}

// NewNullableInt64 creates a new NullableInt64.
// Deprecated: Use NewNullable(val) instead.
func NewNullableInt64(val *int64) *NullableInt64 {
	return NewNullable(val)
}

// NewNullableFloat32 creates a new NullableFloat32.
// Deprecated: Use NewNullable(val) instead.
func NewNullableFloat32(val *float32) *NullableFloat32 {
	return NewNullable(val)
}

// NewNullableFloat64 creates a new NullableFloat64.
// Deprecated: Use NewNullable(val) instead.
func NewNullableFloat64(val *float64) *NullableFloat64 {
	return NewNullable(val)
}

// NewNullableString creates a new NullableString.
// Deprecated: Use NewNullable(val) instead.
func NewNullableString(val *string) *NullableString {
	return NewNullable(val)
}

// NewNullableTime creates a new NullableTime.
// Deprecated: Use NewNullable(val) instead.
func NewNullableTime(val *time.Time) *NullableTime {
	return NewNullable(val)
}

// IsNil checks if an interface value contains a nil pointer.
// This is needed because passing a nil pointer to an interface{} does not make
// the interface itself nil - it contains type information with a nil value.
// Used only for checking MappedNullable interface values in client.go.
func IsNil(i interface{}) bool {
	if i == nil {
		return true
	}
	rv := reflect.ValueOf(i)
	switch rv.Kind() {
	case reflect.Ptr, reflect.Slice, reflect.Map, reflect.Chan, reflect.Func, reflect.Interface:
		return rv.IsNil()
	}
	return false
}

type MappedNullable interface {
	ToMap() (map[string]interface{}, error)
}

// A wrapper for strict JSON decoding
func newStrictDecoder(data []byte) *json.Decoder {
	dec := json.NewDecoder(bytes.NewBuffer(data))
	dec.DisallowUnknownFields()
	return dec
}

// Prevent trying to import "fmt"
func reportError(format string, a ...interface{}) error {
	return fmt.Errorf(format, a...)
}